name: Hello CI # Display name in GitHub UI

on: # Triggers that start this workflow
  push: # Fire on a push event
    branches: [main] # Only when branch is main
  workflow_dispatch: {} # Allow manual run from Actions tab

jobs: # Collection of jobs (run in parallel by default)
  hello: # Job identifier
    runs-on: ubuntu-latest # Use latest Ubuntu runner VM
    steps: # Ordered list of steps for this job
      - name: Checkout code # Step 1: pull repository contents into runner
        uses: actions/checkout@v4 # Reusable action that performs the checkout
      - name: Say hello # Step 2: run a shell command
        run: echo "Hello from GitHub Actions!" # Actual shell command executed
